require('../jakelib/utils.js');

var sources = new jake.FileList();
sources.include('Sources/*.j');
sources.include('Sources/CPArray/*.j');
sources.include('Sources/CPPredicate/*.j');
sources.include('Sources/CPSet/*.j');
sources = sources.toArray();

desc('Create intermediate build directory');
directory('Build/Foundation');

var cppTargets = [];
// Create one preprocessing task per source file
sources.forEach(function(source) {
    var flags = ['-ISources'],
        target = 'Build/Foundation/' + source.replace(/^.*\//, '');
    cppTargets.push(target);
    desc('Preprocess source file:' + source);
    file(target, ['Build/Foundation', source], function () {
        cpp(source, target, flags);
    }, {async: true});
});

task('cpp', cppTargets);

task('default', ['cpp'], function() {
    console.log('# Foundation built');
});
