require('../jakelib/utils.js');

var sources = new jake.FileList();
sources.include('Sources/*.j');
sources.include('Sources/CPArray/*.j');
sources.include('Sources/CPPredicate/*.j');
sources.include('Sources/CPSet/*.j');
sources = sources.toArray();

var BUILD_DIR = '../Build/Foundation';
desc('Create intermediate build directory');
directory(BUILD_DIR);

var cppTargets = [];
// Create one preprocessing task per source file
sources.forEach(function(source) {
    var flags = ['-ISources'],
        target = BUILD_DIR + '/' + source.replace(/^.*\//, '');
    cppTargets.push(target);
    desc('Preprocess source file:' + source);
    file(target, [BUILD_DIR, source], function () {
        cpp(source, target, flags);
    }, {async: true});
});

task('cpp', cppTargets);

task('default', ['cpp'], function() {
    console.log('# Foundation built');
});
